# Generated by Django 3.0.8 on 2020-11-21 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soa',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Appointment'),
        ),
        migrations.AddField(
            model_name='soa',
            name='building_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BuildingPermitApplication'),
        ),
        migrations.AddField(
            model_name='soa',
            name='business_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BusinessPermitApplication'),
        ),
        migrations.AddField(
            model_name='soa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementfiles',
            name='requirement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.ApplicationRequirements'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messeage_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.Thread'),
        ),
        migrations.AddField(
            model_name='lessordetails',
            name='application_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BusinessPermitApplication'),
        ),
        migrations.AddField(
            model_name='businesspermitapplication',
            name='latest_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Department'),
        ),
        migrations.AddField(
            model_name='businesspermitapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='application_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BusinessPermitApplication'),
        ),
        migrations.AddField(
            model_name='businessdeptassessment',
            name='business_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BusinessPermitApplication'),
        ),
        migrations.AddField(
            model_name='businessdeptassessment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Department'),
        ),
        migrations.AddField(
            model_name='businessbasicinformation',
            name='application_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BusinessPermitApplication'),
        ),
        migrations.AddField(
            model_name='businessactivity',
            name='application_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessactivity', to='api.BusinessPermitApplication'),
        ),
        migrations.AddField(
            model_name='buildingrequirementschecklist',
            name='application_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildingchecklist', to='api.BuildingApplicationRequirements'),
        ),
        migrations.AddField(
            model_name='buildingrequirementfiles',
            name='requirement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildingrequirements', to='api.BuildingApplicationRequirements'),
        ),
        migrations.AddField(
            model_name='buildingpermitapplication',
            name='latest_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Department'),
        ),
        migrations.AddField(
            model_name='buildingpermitapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingotherdetails',
            name='application_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BuildingPermitApplication'),
        ),
        migrations.AddField(
            model_name='buildingevaluationfile',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildingevaluationfiles', to='api.Message'),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='application_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BuildingPermitApplication'),
        ),
        migrations.AddField(
            model_name='buildingdeptassessment',
            name='building_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BuildingPermitApplication'),
        ),
        migrations.AddField(
            model_name='buildingdeptassessment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Department'),
        ),
        migrations.AddField(
            model_name='buildingbasicinformation',
            name='application_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BuildingPermitApplication'),
        ),
        migrations.AddField(
            model_name='buildingapplicationrequirements',
            name='application_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='buildingapplicationrequirements', to='api.BuildingPermitApplication'),
        ),
        migrations.AddField(
            model_name='buildingapplicationrequirements',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billfees',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billfees', to='api.Bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='soa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.Soa'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationrequirements',
            name='application_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='businessapplicationrequirements', to='api.BusinessPermitApplication'),
        ),
        migrations.AddField(
            model_name='applicationrequirements',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
