# Generated by Django 3.0.8 on 2020-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201121_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
