# Generated by Django 3.0.8 on 2020-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201121_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermitapplication',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessordetails',
            name='gross_monthly_rental',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
