# Generated by Django 3.0.8 on 2020-11-25 13:48

import api.custom_storage
import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201124_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(null=True, storage=api.custom_storage.PrivateMediaStorage(), upload_to=api.models.MessageAttachment.get_user_image_folder)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageattachments', to='api.Message')),
            ],
        ),
        migrations.DeleteModel(
            name='BuildingEvaluationFile',
        ),
    ]
