# Generated by Django 3.0.8 on 2020-11-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201125_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
