# Generated by Django 3.0.8 on 2020-11-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201130_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='department',
        ),
        migrations.AddField(
            model_name='thread',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
