# Generated by Django 3.0.8 on 2020-12-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201130_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
