# Generated by Django 3.0.8 on 2020-12-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201217_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessactivity',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
