# Generated by Django 3.0.8 on 2020-12-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_businessactivity_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrequirements',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
