# Generated by Django 3.0.8 on 2021-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_applicationrequirements_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivity',
            name='units',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
