# Generated by Django 3.0.8 on 2021-01-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210104_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermitapplication',
            name='application_type',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
