# Generated by Django 3.0.8 on 2021-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_businesspermitapplication_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermitapplication',
            name='is_renewed',
            field=models.BooleanField(default=False),
        ),
    ]
