# Generated by Django 3.0.8 on 2021-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_businesspermitapplication_is_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermitapplication',
            name='renew_local',
            field=models.BooleanField(default=False),
        ),
    ]
