# Generated by Django 3.0.8 on 2021-01-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_businesspermitapplication_renew_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspermitapplication',
            name='renew_local',
        ),
    ]
