# Generated by Django 3.0.8 on 2021-01-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_businesspermitapplication_renew_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermitapplication',
            name='on_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
