# Generated by Django 3.0.8 on 2021-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210113_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivity',
            name='units',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
    ]
