# Generated by Django 3.0.8 on 2021-01-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210114_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='complete_business_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='president_first_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='president_middle_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
