# Generated by Django 3.0.8 on 2021-01-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_businesspermitapplication_last_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermitapplication',
            name='latest_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
