# Generated by Django 3.0.8 on 2021-01-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_businesspermitapplication_latest_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='complete_business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='president_first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='president_last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='president_middle_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='trade_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
