# Generated by Django 3.0.8 on 2021-01-26 01:53

import api.custom_storage
import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210117_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.TextField(max_length=250)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('reference_no', models.TextField(max_length=250)),
                ('file', models.FileField(null=True, storage=api.custom_storage.PrivateMediaStorage(), upload_to=api.models.BankTransaction.get_slip_image_folder)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('soa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Soa')),
            ],
        ),
    ]
