# Generated by Django 3.0.8 on 2021-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_banktransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
