# Generated by Django 3.0.8 on 2021-01-31 12:04

import api.custom_storage
import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_banktransaction_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='file',
            new_name='payment_receipt',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='payment_slip',
            field=models.FileField(null=True, storage=api.custom_storage.PrivateMediaStorage(), upload_to=api.models.BankTransaction.get_slip_image_folder),
        ),
    ]
