# Generated by Django 3.0.8 on 2021-01-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210131_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='payment_receipt',
            new_name='payment_receipts',
        ),
        migrations.RenameField(
            model_name='banktransaction',
            old_name='payment_slip',
            new_name='payment_slips',
        ),
    ]
