# Generated by Django 3.0.8 on 2021-01-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210131_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='payment_receipts',
            new_name='payment_receipt',
        ),
        migrations.RenameField(
            model_name='banktransaction',
            old_name='payment_slips',
            new_name='payment_slip',
        ),
    ]
