# Generated by Django 3.0.8 on 2021-01-31 12:37

import api.custom_storage
import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20210131_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='payment_receipt',
            field=models.FileField(null=True, storage=api.custom_storage.PrivateMediaStorage(), upload_to=api.models.BankTransaction.get_receipt_image_folder),
        ),
    ]
