# Generated by Django 3.0.8 on 2021-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210131_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deliquent',
            field=models.BooleanField(default=False),
        ),
    ]
