# Generated by Django 3.0.8 on 2021-02-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210202_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='is_deliquent',
            new_name='is_delinquent',
        ),
    ]
