# Generated by Django 3.0.8 on 2021-02-19 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210203_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandbankTransaction2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('particulars', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('payor_name', models.TextField(blank=True, null=True)),
                ('payor_email', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('epp_ref_no', models.IntegerField(blank=True, null=True)),
                ('payment_option', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
