# Generated by Django 3.0.8 on 2021-02-19 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_landbanktransaction2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandbankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('particulars', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('payor_name', models.TextField(blank=True, null=True)),
                ('payor_email', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('epp_ref_no', models.IntegerField(blank=True, null=True)),
                ('payment_option', models.CharField(blank=True, max_length=20, null=True)),
                ('merchant_ref_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Soa')),
            ],
        ),
        migrations.DeleteModel(
            name='LandbankTransaction2',
        ),
    ]
