# Generated by Django 3.0.8 on 2021-02-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210219_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soa',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='landbanktransaction',
            name='merchant_ref_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Soa', to_field='reference_number'),
        ),
    ]
