# Generated by Django 3.0.8 on 2021-02-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20210219_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landbanktransaction',
            name='merchant_ref_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Soa', to_field='reference_number'),
        ),
    ]
