# Generated by Django 3.0.8 on 2021-03-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermitapplication',
            name='inspection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
