# Generated by Django 3.0.8 on 2021-04-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20210328_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermitapplication',
            name='series_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
