# Generated by Django 3.0.8 on 2021-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_buildingpermitapplication_series_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingdetails',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AddField(
            model_name='soa',
            name='is_verifed',
            field=models.BooleanField(default=False),
        ),
    ]
