# Generated by Django 3.0.8 on 2021-06-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210621_1300'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='landbanktransaction',
    #         name='merchant_ref_no',
    #         field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Soa'),
    #     ),
    # ]
