# Generated by Django 3.0.8 on 2021-06-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20210621_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landbanktransaction',
            name='merchant_ref_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landbank_transaction', to='api.Soa', to_field='reference_number'),
        ),
    ]
