# Generated by Django 3.0.8 on 2021-06-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20210621_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soa',
            old_name='is_verifed',
            new_name='is_verified',
        ),
    ]
