# Generated by Django 3.0.8 on 2021-10-04 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20210630_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermitFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_year', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('application_id', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='businesspermitfiles', to='api.BusinessPermitApplication')),
            ],
        ),
    ]
