# Generated by Django 3.0.8 on 2021-10-04 13:08

import api.custom_storage
import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_businesspermitfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermitfile',
            name='file',
            field=models.FileField(null=True, storage=api.custom_storage.PrivateMediaStorage(), upload_to=api.models.BusinessPermitFile.get_user_business_permit_folder),
        ),
        migrations.AddField(
            model_name='businesspermitfile',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
