# Generated by Django 3.0.8 on 2021-10-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20211004_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesspermitfile',
            options={'ordering': ['created_at']},
        ),
    ]
