# Generated by Django 3.0.8 on 2021-11-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20211004_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationrequirements',
            options={'ordering': ('-updated_at',)},
        ),
    ]
