# Generated by Django 3.0.8 on 2022-05-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_mobilebuild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebuild',
            name='for_maintenance',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='mobilebuild',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
