# Generated by Django 3.0.8 on 2023-07-24 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20220606_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PisoPayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('settlement_status', models.TextField(blank=True, null=True)),
                ('reference_count', models.TextField(blank=True, null=True)),
                ('reference_number', models.TextField(blank=True, null=True)),
                ('transaction_status_all', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('payment_channel_code', models.TextField(blank=True, null=True)),
                ('customer_name', models.TextField(blank=True, null=True)),
                ('customer_email', models.TextField(blank=True, null=True)),
                ('customer_phone', models.TextField(blank=True, null=True)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('posted_date', models.DateTimeField(null=True)),
                ('timestamp', models.TextField(blank=True, null=True)),
                ('hd', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('trace_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pisopay_transaction', to='api.Soa', to_field='reference_number')),
            ],
        ),
    ]
