from django.urls import path, include
from api import views
urlpatterns = [
    path('sendmail/', views.SendMail.as_view()),
    path('password/reset/confirm/<str:uid>/<str:token>',views.Redirect.as_view()),
    path('barangay/', views.BarangayList.as_view()),
    path('api/business-permit-application/',views.BusinessPermitApplicationView.as_view()),
    path('api/business-basic-information/',views.BasicInformationView.as_view()),
    path('api/business-details/',views.BusinessDetailsView.as_view()),
    path('api/business-lessor-details/',views.LessorDetailsView.as_view()),
    path('api/business-activity/',views.BusinessActivityViews.as_view()),

    path('api/building-permit-application/',views.BuildingPermitApplicationViews.as_view()),
    path('api/building-basic-information/',views.BuildingBasicInformationViews.as_view()),
    path('api/building-details/',views.BuildingDetailsViews.as_view()),
    path('api/building-other-details/',views.BuildingOtherDetailsViews.as_view()),
    path('api/file-upload/',views.FileUploadView.as_view()),
    path('api/application-requirements/',views.ApplicationRequirementsView.as_view()),
    path('api/building-file-upload/',views.BuildingFileUploadView.as_view()),
    path('api/building-application-requirements/',views.BuildingApplicationRequirementsView.as_view()),
    path('api/get-level/',views.UserTypeView.as_view()),
    path('api/business-profile/', views.BusinessProfileListView.as_view()),
    path('api/building-profile/', views.BuildingProfileViews.as_view()),
    path('api/real-property-profile/', views.RealPropertyProfileViews.as_view()),
    path('api/threads/', views.ThreadView.as_view()),
    path('api/user-inquiry/', views.UserInquiryList.as_view()),
    path('api/user-remarks/', views.UserRemarksList.as_view()),
    path('api/messages/', views.MessageView.as_view()),
    path('api/inquiry/', views.InquiryView.as_view()),
    path('api/resolve-inquiry/', views.ThreadResolveView.as_view()),
    path('api/verify-enrollment/', views.VerifyEnfrollmentView.as_view()),
    path('api/building-checklist/', views.BuildingRequirementsChecklistViews.as_view()),
    path('api/building-application/', views.BuildingPermitApplicationProfileView.as_view()),
    path('api/business-application/', views.BusinessPermitApplicationProfileView.as_view()),
    path('api/business-remarks-thread/', views.BusinessRemarksThread.as_view()),
    path('api/building-remarks-thread/', views.BuildingRemarksThread.as_view()),
    path('api/appointment/', views.AppointmentView.as_view()),
    path('api/appointment-limit/', views.AppointmentLimitView.as_view()),
    path('api/soa-list/', views.SoaListView.as_view()),
    path('api/business-assessment-result/', views.UserBusinessAssessmentResult.as_view()),
    path('api/building-assessment-result/', views.UserBuildingAssessmentResult.as_view()),
    path('api/user-appointment-list/', views.UserAppointmentList.as_view()),
    path('api/user-business-application-list/', views.UserBusinessApplicationList.as_view()),
    path('api/user-building-application-list/', views.UserBuildingApplicationList.as_view()),
    path('api/user-soa/', views.UserSoaView.as_view()),
    path('api/message-attachment-upload/',views.MessageAttachmentUploadView.as_view()),
    path('api/department-list/', views.DepartmentListView.as_view()),
    path('api/business-activity-renewal/', views.BusinessActivityRenewalView.as_view()),
    path('api/business-requirement-renewal/', views.BusinessRequirementsRenewal.as_view()),
    path('api/business-active-requirements/', views.BusinessActiveRequirements.as_view()),
    path('api/renew-business-application/', views.RenewBusinessApplicationView.as_view()),
    path('api/payment-success/', views.LandBankSuccessRedirect.as_view()),
    path('api/pisopay/payment-success/', views.PisoPaySuccessCallback.as_view()),
    path('api/payment-error/', views.LandBankErrorRedirect.as_view()),
    path('api/bank-transaction/', views.BankTransactionView.as_view()),
    path('api/bank-transaction-list/', views.UserBankTransactionListView.as_view()),
    path('api/landbank-transaction-list/', views.UserLandbankTransactionListView.as_view()),
    path('api/pisopay-transaction-list/', views.UserPisoPayTransactionListView.as_view()),
    path('api/faq/', views.FaqView.as_view()),
    path('api/download-business/', views.DownloadBusinessView.as_view()),
    path('api/download-invoice/', views.DownloadInvoiceView.as_view()),
    path('api/download-appointment/', views.DownloadAppointmentView.as_view()),
    path('api/active-mobile-build', views.ActiveMobileView.as_view()),
    path('api/mobile-build-status', views.MobileBuildStatus.as_view()),
    path('api/mobile-downloads-count/', views.MobileDownloadsCountView.as_view()),
    path('api/download-building/', views.DownloadBuildingView.as_view()),
    path('api/pisopay/session/', views.GetPisoPaySessionView.as_view()),
    path('api/pisopay/token/', views.GeneratePisoPayTokenView.as_view())
]

